### PR TITLE
Add survey links to basic template

### PR DESCRIPTION
**Pull request by maneesha**

### CODE REVIEW

**Comment by tracykteal** [comment]
Thanks, it will be good to have those directly included. Should we add a line that says something like

"When filling out the survey, please select the workshop that you will be attending from the drop-down list."

**Comment by maneesha** [comment]
I thought about saying that, but those instructions are in the survey itself so I thought that would be redundant.  I've found that the more instructions you give people to read, the less they actually end up reading.  So I figure we should keep it simple and non-repetitive.

**Comment by gvwilson** [comment]
+1

**Comment by tracykteal** [comment]
Sounds good, thanks!

**Pull request merged**
