### PR TITLE
Commented out instructions in header

### PR DESCRIPTION
**Pull request by ACharbonneau**
As written, the template webpage won't compile. This PR comments out the instructions for filling in the header lines, and adds empty brackets for lists. which fixes most, but not all of the problem. It still gives this error:

> INFO: Testing "./index.html"
> ERROR: There are superfluous categories
> ERROR: Offending entries: set(['day1_am', 'day1_pm', 'day2_pm', 'day2_am'])

But it does render a webpage.

### CODE REVIEW

**Comment by tracykteal** [comment]
Thanks, yes those instructions should be commented out. The superfluous categories part was fixed with https://github.com/datacarpentry/workshop-template/pull/9

I noticed the SWC template has the comments aligned in a column https://github.com/swcarpentry/workshop-template/blob/gh-pages/index.html and it makes it a little easier to read. Should we do that here as well?

**Comment by ACharbonneau** [comment]
Yes. I made the commented out bits and FIXMEs into fake columns...I think that makes it look nicer than the SWC version, it's easier to see if a FIXME got missed.
(Also pulled in the other changes, etc, so current pull request is good)

**Comment by hlapp** [comment]
@tracykteal I'm good to merge this - any objections?

**Comment by qingpeng** [comment]
aha, I had the same problem when I tried to compile the webpage. It's more clear if the instructions are commented out.

**Pull request merged**
