### PR TITLE
A (reasonably) generic workshop site template

### PR DESCRIPTION
**Pull request by apawlik**
Still need to add instructions on how to use that, license and such.
Tried to preserve history as much as possible picking the basic framework from https://github.com/datacarpentry/archive-datacarpentry/tree/gh-pages and then adding some of the tweaks I had in https://github.com/apawlik/2015-06-24-dc-utrecht/tree/gh-pages
I don't thing I've done it quite the right was as even though most of this I think originated from https://github.com/swcarpentry/workshop-template/tree/gh-pages, you can't see it in the history :-( Though I hope it's acceptable to fix it in CONTRIBUTORS.md listing everyone who ever worked on these files.

### CODE REVIEW

**Comment by tracykteal** [comment]
I've also taken this template and made some adaptations, including updating the install instructions and inspired by Leah Wasser, using YAML to set what's in those instructions like here:
https://github.com/datacarpentry/2015-05-03-NDIC/tree/gh-pages  
http://datacarpentry.github.io/2015-05-03-NDIC/  
install: http://datacarpentry.github.io/2015-05-03-NDIC/install.html

I didn't preserve history though, so I think the thing to do is to start the repo with these files, and then I can adapt them. 

I see 76 files are in the commit. Do we need all 76 (I see some image files that I don't think we need). Do we want to clean up first and then make the first commit, or just go ahead and commit and then clean up?

**Comment by fmichonneau** [comment]
This uses the old workshop template from software carpentry. Recently, we
upgraded it to remove a lot of things that were not needed, and it uses a
more recent version of the CSS library bootstrap. If possible, I think we
should use it.

**Comment by tracykteal** [comment]
I agree, I like the new workshop template (just saw it deployed here http://swcarpentry.github.io/2015-05-30-hastac-swc/). I think we should start with that, and then modify for Data Carpentry specifics. We do have more variability in topics, so we might want to make those sections more YAML driven than static content for instance, as well as just changing things like logos.

@apawlik would it be OK to use the new template? If so, @fmichonneau could you bring that template over here and maintain history?

**Comment by apawlik** [comment]
OK. Sorry, I simply didn't know which way we're going with this. I though that we're steering away from SWC solutions since they got relatively more complex. I'm happy to work with @fmichonneau on this.

**Comment by tracykteal** [comment]
I think that's true for the lesson template where things have to be compiled, but for the workshop template, it looks like it's just the github Jekyll. Is that right, or am I missing something?

**Comment by fmichonneau** [comment]
Yes it's correct. Just Jekyll. I'm pretty busy at least until the weekend
but I can start putting something together and you can provide feedback as
needed.

**Comment by gvwilson** [comment]
The lessons are more complicated, but the workshop template is still 
just Jekyll.  We did play around a bit with inclusions, conditionals, 
and YAML, but feedback from novice instructors was "it's a lot easier to 
just edit the page and delete things I don't want".

If we do decide to make changes to accommodate DC-specific things, we 
can/should modify `tools/check.py` to check things before commits.

**Comment by tracykteal** [comment]
I just created a PR that moves all the SWC files over here and preserves history.  https://github.com/datacarpentry/workshop-template/pull/2 
If we want to start with that PR, then we can just modify the files from there in this repo.

If that seems like a reasonable approach, maybe someone can approve the PR? Or let me know if I should do it a different way.

**Comment by hlapp** [comment]
Frankly, I'm skeptical that we should spend much effort on this. This is one of the things where it's easy to reinvent what SWC has already done, and for which SWC will continue to have a lot more resources (i.e., larger community of potential contributors).

Here's an example where we used the SWC workshop template for something that SWC surely didn't anticipate it being used for, the inaugural [Reproducible Science workshop](https://github.com/Reproducible-Science-Curriculum/2015-05-14-reproducible-science-duke/). The repo has the [full commit history](https://github.com/Reproducible-Science-Curriculum/2015-05-14-reproducible-science-duke/commits/gh-pages?page=1). The adaptations here were arguably exceptionally complex (essentially a re-branding), yet it wasn't too much work to do even that. (Only the commit history from April and past is specific to this website. And you probably see the trial and error in the adaptions.)

In essence what I'm trying to suggest is that I think we would be best off if we set up our own template such that the SWC template would remain the master template that we can easily switch back to, for example because we keep our customizations light and well compartmentalized so that they can be re-applied to a future version of the SWC template.

If the two templates diverged to the extent that bringing in a new SWC template version would be painful, that would be a bad thing and loss of synergy IMHO.

**Comment by tracykteal** [comment]
Yes, I agree. So does it make sense to just move the current SWC template over here and adapt like I  proposed in https://github.com/datacarpentry/workshop-template/pull/2 

Then if we have major suggestions we could contribute them to the SWC template and use here.

**Comment by ethanwhite** [comment]
Solved elsewhere.

**Pull request closed without merging**
